---
title: "CPIA Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    smooth_scroll: true
    theme: 
      version: 4
      bg: "#f0f8ff"
      fg: "#34495e"
      primary: "#2c3e50"
      secondary: "#5dade2"
runtime: shiny
---

```{css, echo=FALSE}
.chart-wrapper .chart-title {
  text-align: center !important;   /* center titles above each chart */
}

.section.level1 h2, 
.section.level2 h2 {
  text-align: center !important;   /* center row/column group headers */
}
```

```{r setup, echo = FALSE, include=FALSE, message=FALSE, warning=FALSE}

library(dplyr)
library(tidyr)
library(flexdashboard)
library(shiny)
library(ggplot2)
library(plotly)

devtools::load_all()

# cpia <- cpia |> split(cpia$country_group)


cpia_tbl <- 
  cpia |>
  pivot_longer(cols = starts_with("q"),
               names_to = "indicator",
               values_to = "value") |>
  merge(cpia_indicators |> dplyr::select(variable, question) |> unique(),
        by.x = "indicator", by.y = "variable",
        all.x = TRUE) |> 
  as_tibble()


```



```{r}


gen_plot <- function(var,
                     plot_df, 
                     country_name,
                     miss_x = 0.5,
                     miss_y = 0.5,
                     plot_title,
                     footstr, 
                     anote_x = 0.5,
                     anote_y = -0.1,
                     anote_size = 10,
                     ylim_min = 1,
                     ylim_max = 6){
  
  # region_chr <- unique(plot_df$region[plot_df$country_name == country_name])
  # region_chr <- region_chr[!is.na(region_chr)]
  # Filter country data
  plot_df <- 
    bind_rows(plot_df |>
                dplyr::filter(country_name == country_name & indicator == var))
 
  has_country_logical <- any(!is.na(plot_df$value[[plot_df$country_group == 0]]))
  # has_regcomp_logical <- any(!is.na(plot_df$value[[plot_df$country_group == 1]]))

  # if (!has_country_logical & !has_regcomp_logical){
  #   p <- ggplot() + 
  #     annotate("text", x = miss_x, y = miss_y, 
  #              label = "Missing country & regional data") + 
  #     theme_void()  } 
  if (!has_country_logical) {
    p <- 
      ggplot() + 
      annotate("text", x = miss_x, y = miss_y, label = "Missing country data") + 
      theme_void()

  } else {

    # plot_df$var <- plot_df[[var]]
    # plot_df$var_g <- plot_df[[paste0(var, "_g")]]
    # plot_df$var_r <- plot_df[[paste0(var, "_r")]]

    p <- 
      ggplot(plot_df, aes(x = year)) +
      geom_line(aes(y = value), linewidth = 0.6) +
      geom_point(aes(y = value, text = paste0(country_name, ": ", round(value, 2)))) +
      labs(title = NULL, x = NULL, y = NULL, caption = footstr, color = "") +
      ylim(ylim_min, ylim_max) +
      theme_minimal() +
      theme(
        legend.position = "bottom",        # <<--- legend at bottom
        legend.title = element_blank(),
        legend.text = element_text(size = 10),
        plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
        plot.caption = element_text(hjust = 0, size = 10, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
      ) + scale_x_continuous(breaks = seq(min(plot_df$year), max(plot_df$year), 1))
    
    }
  return(p)
}


ggplotly_wrap <- 
  function(var_def = "",
           ...){
    
    plot_obj <- 
    plotly::ggplotly(tooltip = "text",
                     ...) %>%
    layout(
      legend = list(
        orientation = "h",
        x = 0.5, xanchor = "center", y = -0.13
      ),
      margin = list(t = 60, b = 120),
      annotations = list(
        text = var_def,
        x = 0.5, y = -0.23,  # center horizontally
        xref = "paper", yref = "paper",
        xanchor = "center", yanchor = "top",  # << center anchor
        showarrow = FALSE,
        font = list(size = 10, color = "black")
      )
    )
    
    return(plot_obj)

}



```






Dashboard <i class="fa fa-tachometer-alt"></i>
=======================================================================================================================


Column {.sidebar}
----------------------------------------------------------------------------------------------------------------------

Please select your country of interest:

```{r}

shiny::fluidPage(

  selectInput(inputId = "country_name",
              label = "",
              choices = sort(unique(cpia_tbl$country_name))),

  hr(),
  
  downloadButton("download_report", "Download Report",
                 style = "width:215px; height:40px;"),
  
  br(), br(), ### adds two line breaks for spacing
  
  downloadButton("download_data_doc", "Download Full Dataset",
               style = "width:215px; height:40px;")
  

)


output$download_report <- downloadHandler(
  filename = function() {
    paste0("CPIA_Factsheet_", input$country_name, ".pdf")
  },
  content = function(file) {
    # render directly to working directory
    out_file <- paste0("CPIA_Factsheet_", input$country_name, ".pdf")
    
    rmarkdown::render(
      input = "report.Rmd",
      output_format = "pdf_document",
      output_file = out_file,
      params = list(
        country_name = input$country_name,
        cpia = cpia$country
      ),
      envir = new.env(parent = globalenv())
    )
    
    # copy rendered pdf to expected location
    file.copy(out_file, file, overwrite = TRUE)
  }
)


# Server
output$download_data_doc <- downloadHandler(
  filename = function() {
    "cpia_data_documentation.xls"
  },
  content = function(file) {
    file.copy("cpia_data_documentation.xls", file, overwrite = TRUE)
  }
)


```


## {data-height=50}
----------------------------------------------------------------------------------------------------------------------

```{r, results='asis', echo=FALSE}
cat('
<div style="
  display:block;
  width:100%;
  text-align:center;
  font-size:22px;
  font-weight:bold;
  margin:0;
  padding:6px 0 2px 0;
  border-bottom:1px solid #ccc;
">
  CPIA Metrics
</div>
')
```

Row 
---------------------------------------------------------------------------------------------------------------------------------


### 

```{r}


tags$div(
  style = "text-align:center; font-size:14px; font-weight:600; margin: 0 0 4px 0;",
  unique(cpia_tbl$question[cpia_tbl$indicator == "q12a"])
)
hr(style = "margin-top:2px; margin-bottom:6px;")


# output$country_plot <- renderPlotly({
#   
#   req(input$country_name)
#   
#   p2 <- gen_plot(var = "q12a",
#                  plot_df = cpia_tbl,
#                  country_name = input$country_name,
#                  plot_title = unique(cpia_tbl$question[cpia_tbl$indicator == "q12a"]),
#                  footstr = NULL)
# 
# 
#   ggplotly_wrap(p = p2,
#                 var_def = "")
# })
# 
# plotlyOutput("q12a", height = "450px")


output$country_plot <- renderPlotly({
  req(input$country_name)

# Create the plot data

  plot_df <- cpia_tbl

# Generate the ggplot object

  p <- gen_plot(
    var = "q12a",   # for example; you can later make this reactive too
    plot_df = plot_df,
    country_name = input$country_name,
    plot_title = paste("CPIA Q12a Trend for", input$country_name),
    footstr = "Source: World Bank CPIA dataset"
)

# Convert to plotly

  ggplotly_wrap(var_def = "CPIA Q12a: Quality of budgetary processes", p)
  
})


```





